In [2]:
import numpy as np

# 48頁

In [2]:
A = np.array([1 ,2 ,3 ,4])

In [3]:
print(A)

[1 2 3 4]


In [4]:
np.ndim

<function numpy.ndim(a)>

In [5]:
np.ndim(A)

1

In [7]:
A.shape

(4,)

In [10]:
A.shape[0]

4

In [11]:
B = np.array([ [1 ,2] ,[3 ,4] ,[5 ,6] ])

In [12]:
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
np.ndim(B)

2

In [18]:
B.shape

(3, 2)

In [19]:
B.shape[0]

3

In [20]:
B.shape[1]

2

# 62頁

In [3]:
a = np.array([0.3 ,2.9 ,4.0])

In [4]:
exp_a = np.exp(a)

In [5]:
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [6]:
sum_exp_a = np.sum(exp_a)

In [7]:
print(sum_exp_a)

74.1221542101633


In [8]:
y = exp_a / sum_exp_a

In [9]:
print(y)

[0.01821127 0.24519181 0.73659691]


In [14]:
# 這個算法 存在問題，萬一 a 陣列 裡面的值 大於某個數
# 例如 exp(1000) 會回傳 inf 無限大的值 所以需要改良
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [22]:
# 驗證一下 改良版的步驟

# exp(1010) 、 exp(1000) 、 exp(990) 會有 inf 問題

a = np.array([1010 ,1000 ,990])
y = np.exp(a) / np.sum(np.exp(a)) # 計算 softmax 值
print(y)

[nan nan nan]


C:\Users\Big data\.conda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: overflow encountered in exp
  
C:\Users\Big data\.conda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  


In [23]:
c = np.max(a) #1010
a - c

array([  0, -10, -20])

In [24]:
# 將 原本的 a 陣列裡 扣除 陣列裡最大值 
# 例子 a 中 1010 為三個數裡面的最大值

np.exp(a-c) / np.sum(np.exp(a-c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [29]:
# 寫成 改良版函式

def softmaxB(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [30]:
softmaxP(a)

array([0.01821127, 0.24519181, 0.73659691])

# 64 頁

In [35]:
a = np.array([0.3 ,2.9 ,4.0])
y = softmaxP(a)
print(y)

[0.01821127 0.24519181 0.73659691]


In [36]:
np.sum(y)

1.0